### ISSUE TITLE
About ScanNet data format

### ISSUE THREAD

**Issue by weiyithu** [magicleap/Atlas#16]
Hi @zmurez, I wonder if the pose/*.txt are same with the files extracted from ScanNet toolkits (SensorData.py). Now I cannot reproduce your results using  the data provided by ScanNet official code. If possible, could you provide an example scene in ScanNet with its scene id?

**Comment by zmurez** [comment]
Sorry for the delay. Were you able to figure it out? Yes, all the data (including pose/*.txt) is extracted using `SensorData.py` from the ScanNet toolkit. Unfortunately I am not able to provide a pre-unpacked scene from the dataset due to Scannet terms of use, but I do provide a sample scene of my own which is a zip file (see `Data Preperation/sample` in the README).
